version: 2
nightly:
  triggers:
    - schedule:
        cron: "*/2 * * * *"
        filters:
          branches:
            only:
              - master
  jobs:
    build:
      steps:
        name: build registry
        command: npm run build:registry
jobs:
  build:
    docker:
      - image: "circleci/node:lts-browsers"
    steps:
      - checkout
      - run:
          name: install
          command: npm ci
      - run:
          name: lint
          command: npm run lint
      - run:
          name: test
          command: npm run test
      - run:
          name: build
          command: npm run build
      - run:
          name: integration
          command: ./scripts/integration-headless.sh
